server:
  port: 3344

spring:
  application:
    name: cloud0config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/13327955131/springcloud.git   #github 远程项目地址
          search-paths:
            - springcloud                 #github 项目名
          force-pull: true
          username: 281008187@qq.com      #github 账号
          password: Aq521295475295        #github 密码
      label: master

#rabbitmq相关配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

  ##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'




eureka:
  client:
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
            defaultZone: http://localhost:7001/eureka    #单机版写一个
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版

