server:
  port: 9002
spring:
  application:
    name: cloud-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #配置Nacos 地址

management:
  endpoints:
    web:
      exposure:
        include: '*'